version: '3.8'

services:
  algorithms:
    container_name: algorithms
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: denemedb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - 9001:80
    depends_on:
      - mysql_db

volumes:
  mysql_data:
